# Site settings
title: Blogging and Such
email: 
description: > # this means to ignore newlines until "baseurl:"
  Hello is this working ahh jekyll you cray
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://huntercaron.com/" # the base hostname & protocol for your site

twitter_username: Hunter
github_username:  Hunter

# Build settings
markdown: kramdown
